In [1]:
import torch

In [2]:
N = 10 

D_in = 1
D_out = 1

X = torch.randn(N, D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

In [ ]:
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(W)
print(b)

tensor([[-0.1419]], requires_grad=True)
tensor([-1.0390], requires_grad=True)


In [11]:
y_hat = X @ W + b

print(y_hat[:3])
print(y_true[:3])

tensor([[-0.9130],
        [-1.0627],
        [-1.0298]], grad_fn=<SliceBackward0>)
tensor([[-0.6342],
        [ 1.4388],
        [ 1.0325]])


In [13]:
error = y_hat - y_true
squared_error = error **2
loss = squared_error.mean()

print(loss)

tensor(4.3038, grad_fn=<MeanBackward0>)


In [14]:
loss.backward()

print(W.grad)
print(b.grad)

tensor([[-1.0937]])
tensor([-3.0837])


In [22]:
learning_rate, epochs = 0.01, 500

W, b = torch.randn(1, 1, requires_grad=True), torch.randn(1, requires_grad=True)

for epoch in range(epochs):
    y_hat = X @ W + b
    loss = torch.mean((y_hat-y_true)**2)

    loss.backward()

    with torch.no_grad():
        W -= learning_rate * W.grad; b -= learning_rate * b.grad

    if epoch % 50 == 0:
        print(f"Epoch {epoch:02d}: Loss={loss.item():.4f}, W={W.item():.3f}, b={b.item():.3f}")
        print(f"\nFinal Parameters: W={W.item():.3f}, b={b.item():.3f}")
        print(f"True Parameters: W=2.000, b=1.000")
    
    W.grad.zero_(); b.grad.zero_()


Epoch 00: Loss=3.6359, W=-0.797, b=0.871

Final Parameters: W=-0.797, b=0.871
True Parameters: W=2.000, b=1.000
Epoch 50: Loss=1.3730, W=0.209, b=0.632

Final Parameters: W=0.209, b=0.632
True Parameters: W=2.000, b=1.000
Epoch 100: Loss=0.6007, W=0.819, b=0.655

Final Parameters: W=0.819, b=0.655
True Parameters: W=2.000, b=1.000
Epoch 150: Loss=0.2767, W=1.208, b=0.733

Final Parameters: W=1.208, b=0.733
True Parameters: W=2.000, b=1.000
Epoch 200: Loss=0.1318, W=1.464, b=0.806

Final Parameters: W=1.464, b=0.806
True Parameters: W=2.000, b=1.000
Epoch 250: Loss=0.0659, W=1.634, b=0.863

Final Parameters: W=1.634, b=0.863
True Parameters: W=2.000, b=1.000
Epoch 300: Loss=0.0358, W=1.748, b=0.903

Final Parameters: W=1.748, b=0.903
True Parameters: W=2.000, b=1.000
Epoch 350: Loss=0.0221, W=1.825, b=0.931

Final Parameters: W=1.825, b=0.931
True Parameters: W=2.000, b=1.000
Epoch 400: Loss=0.0158, W=1.877, b=0.950

Final Parameters: W=1.877, b=0.950
True Parameters: W=2.000, b=1.000
E