In [1]:
import torch

In [3]:
N = 10 

D_in = 1
D_out = 1

X = torch.randn(N, D_in)

linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

print(f"Layer's weight (W): {linear_layer.weight}\n")
print(f"Layer's bias (B): {linear_layer.bias}\n")

y_hat_nn = linear_layer(X)

print(f"Output of nn.Linear (first 3 rows):\n {y_hat_nn[:3]}")

Layer's weight (W): Parameter containing:
tensor([[0.7943]], requires_grad=True)

Layer's bias (B): Parameter containing:
tensor([-0.5849], requires_grad=True)

Output of nn.Linear (first 3 rows):
 tensor([[ 0.2084],
        [-0.7596],
        [ 0.1012]], grad_fn=<SliceBackward0>)


In [ ]:
relu = torch.nn.ReLU()
sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])
ReLU_activated_data = relu(sample_data)

print(f"Original Data: {sample_data}")
print(f"Data after ReLU: {ReLU_activated_data}")

Original Data: tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after ReLU: tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])


In [5]:
gelu = torch.nn.GELU()
gelu_activated_data = gelu(sample_data)

print(f"Original Data: {sample_data}")
print(f"Data after ReLU: {gelu_activated_data}")

Original Data: tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after ReLU: tensor([-0.0455, -0.1543,  0.0000,  0.3457,  1.9545])


In [ ]:
softmax = torch.nn.Softmax(dim=-1)
logits = torch.tensor([[1.0, 3.0, 0.5, 1.5], [-1.0, 2.0, 1.0, 0.0]])
probabilities = softmax(logits)

print(f"Output Probabilities:\n {probabilities}")
print(f"Sum of probabilities for item 1: {probabilities[0]}.sum()")

Output Probabilities:
 tensor([[0.0939, 0.6942, 0.0570, 0.1549],
        [0.0321, 0.6439, 0.2369, 0.0871]])
Sum of probabilities for item 1: tensor([0.0939, 0.6942, 0.0570, 0.1549]).sum()


: 