In [1]:
import torch

In [2]:
data = [[1,2,3],[1,2,3]]
my_tensor = torch.tensor(data)
print(my_tensor)

tensor([[1, 2, 3],
        [1, 2, 3]])


In [3]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(random)

tensor([[ 0.9274,  0.9222,  1.6447],
        [ 1.7544, -0.2099,  0.6735]])


In [4]:
template = torch.tensor([[1,2],[3,4]])

rand_like = torch.randn_like(template, dtype=torch.float)
print(template)
print(rand_like)

tensor([[1, 2],
        [3, 4]])
tensor([[-0.1188, -0.1594],
        [ 1.5888,  0.3537]])


In [5]:
tensor = torch.randn(2,3)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([2, 3])
torch.float32
cpu


In [6]:
x_data = torch.tensor([[1.,2.],[3.,4.]])

w = torch.tensor([[1.0],[2.0]], requires_grad=True)

print(x_data.requires_grad)
print(w.requires_grad)

False
True


In [7]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b
z = x*y

print(z)
print(z.grad_fn)
print(y.grad_fn)
print(a.grad_fn)

tensor(20., grad_fn=<MulBackward0>)
None


In [8]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[20,30],[40,50]])

element_wise_product = a * b
print(element_wise_product)

tensor([[ 20,  60],
        [120, 200]])


In [9]:
m1 = torch.tensor([[1,2,3],[4,5,6]])
m2 = torch.tensor([[7,8],[9,10],[11,12]])

matrix_product = m1 @ m2
print(matrix_product)

tensor([[ 58,  64],
        [139, 154]])


In [10]:
score = torch.tensor([[10.,20.,30.],[5.,10.,15.]])

average_scores = score.mean()
average_per_assignment = score.mean(dim=0)
average_per_student = score.mean(dim=1)

print(average_scores)
print(average_per_assignment)
print(average_per_student)

tensor(15.)
tensor([ 7.5000, 15.0000, 22.5000])
tensor([20., 10.])


In [11]:
x = torch.arange(12)
print(x)

x = x.reshape(3,4)
col_2 = x[:,2]
print(x)
print(col_2)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  6, 10])


In [12]:
scores = torch.tensor([
    [10,0,5,20,1],
    [1,30,2,5,0]
])

best_indices = torch.argmax(scores, dim=1)
print(best_indices)

tensor([3, 1])


In [13]:
data = torch.tensor([
    [10,11,12,13],
    [20,21,22,23],
    [30,31,32,33]
])

indices_to_select = torch.tensor([[2], [0],[3]])

selected_values = torch.gather(data, dim=1, index=indices_to_select)

print(selected_values)

tensor([[12],
        [20],
        [33]])
